### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by martinvelez** [DDNStorage/collectd#2] opened 2019-02-07 00:43 UTC
I have done the following:

1) downloaded the repo.
2) installed various dependencies via yum.
3) ./configure
4) make

But make is giving me an error related to **uthash.h**.  I searched the [ISO](http://lustrefs.cn/monitor/) and did not find it there.  I searched online and it appears to be a [single header file](https://troydhanson.github.io/uthash/userguide.html#_download_uthash).  How did you make collectd?

```
[root@hostname collectd-master-ddn]# make
  YACC     src/liboconfig/parser.c
updating src/liboconfig/parser.h
  POD2MAN  src/collectd.1
  POD2MAN  src/collectd.conf.5
  POD2MAN  src/collectd-email.5
.
.
.
  CC       src/zookeeper.lo
  CCLD     zookeeper.la
  CC       src/filedata_la-filedata.lo
In file included from src/filedata_read.h:24:0,
                 from src/filedata.c:25:
src/filedata_config.h:29:20: fatal error: uthash.h: No such file or directory
 #include <uthash.h>
                    ^
compilation terminated.
make[1]: *** [src/filedata_la-filedata.lo] Error 1
make[1]: Leaving directory `/root/github/collectd-master-ddn'
make: *** [all] Error 2
[root@hostname collectd-master-ddn]# 
```

**Comment by martinvelez** [comment] 2019-02-07 01:40
1. I downloaded [uthash.h](https://raw.githubusercontent.com/troydhanson/uthash/master/src/uthash.h) from its github repo.  
1. I placed it in the **src** directory and tried running **make** again.  

This time it appears like **make** succeeded.

```
[root@hostname collectd-master-ddn]# make
make  all-am
make[1]: Entering directory `/root/github/collectd-master-ddn'
  CC       src/libcollectdclient/libcollectdclient_la-client.lo
.
.
.
make[2]: Leaving directory `/root/github/collectd-master-ddn/buildperl'
make[1]: Leaving directory `/root/github/collectd-master-ddn'
[root@hostname collectd-master-ddn]# echo $?
0
```

**Comment by LiXi-storage** [comment] 2019-02-07 04:48
There are some configure option we need to add to avoid compile failure caused by unnessary plugin. Following is the example of compiling the Collectd:

sh ./build.sh
./configure --enable-write_tsdb --enable-debug --enable-dist --enable-nfs --disable-java --disable-amqp --disable-gmond --disable-nut --disable-pinba --disable-ping --disable-varnish $EXTRA_CONFIG_OPTION
make
make dist-bzip2
mkdir {BUILD,RPMS,SOURCES,SRPMS}
mv collectd-*.tar.bz2 ${WORKSPACE}/SOURCES/
rpmbuild -ba --with write_tsdb --with nfs --without java --without amqp --without gmond --without nut --without pinba --without ping --without varnish --without dpdkstat $EXTRA_OPTION --define="rev $rev" \
--define "_topdir ${WORKSPACE}" contrib/redhat/collectd.spec

For CentOS6, you might want to export:

EXTRA_OPTION="--without turbostat"
EXTRA_CONFIG_OPTION="--disable-turbostat"

For CentOS7, you might want to export:

EXTRA_OPTION="--without ganglia --without memcachec -without rrdcached --without rrdtool --without lvm"
EXTRA_CONFIG_OPTION="--disable-ganglia --disable-memcachec --disable-rrdcached --disable-rrdtool --disable-lvm"

**Comment by LiXi-storage** [comment] 2019-02-26 02:02
Martin, I am closing this ticket assuming that you've successfully built it. Please feel free to reopen this ticket or open other tickets if you have further problem.

**Closed as completed** 2019-02-26 02:24 UTC
